version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443" #cambiar a 80:80, INVESTIGAR 443:443
    volumes:
      - web:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - web:/var/www/html
    networks:
      - inception
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    restart: always #on-failure?? lo mismo pa los otros
    #expose:
    #  - "9000" ESTO ES NECESARIO?
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    restart: always
    #expose:
    #  - "3306" ESTO ES NECESARIO?

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/database
  web:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/web
networks:
  inception:
    driver: bridge