CREATE DATABASE wordpress;
CREATE USER 'nortolan'@'%' IDENTIFIED BY '115!hola';
GRANT ALL PRIVILEGES ON *.* TO 'nortolan'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

--REVISAR/QUITAR DATOS DE AQUI (METERLOS EN EL ENV)